### ISSUE TITLE
Добавить бандлинг

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#1]
1. Все подключаемые css файлы собирать в один, app.css.  Посмотри в галпе должен быть плагин который это делает (типа gulp-concat)
2. Все подключаемые js-файлы собирать в один, app.js.  Посмотри в галпе должен быть плагин который это делает. Причем сначала должен идти код модулей компонентов (который не требует построенного ДОМ дерева), а в конце уже инциализация компонентов на странице после ДОМ ( DOMContentLoaded)
3. Все ресурсы подключать локально, без CDN ( я увидел unpkg, google fonts ). Сейчас нам лучше перейти на локальное хранение всех ресурсов
4. Соотв-но шрифты тоже отдавать с локалки
5. Посмотри, галп при сборке бандла может генерировать хеш-сумму, и соотв вставлять ее в названиеб типа app-dc55d3fd.css. Тогда автоматически будет работать кеш-бастинг,  не надо изобретать костыли для него

**Comment by Bioss7** [comment]
1. У меня gulp собирает в минифицированную версию
2. У меня gulp собирает в минифицированную версию
3. Про это знаю, подключал для быстрого старта, будет перенесено 
4. Шрифты 
5. Про хеш-сумму можно подробнее и кеш-бастинг?

**Comment by Bioss7** [comment]
Сделано
