### ISSUE TITLE
Релиз 0.0.1:  Разместить файлы на ФТП

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#12]
После того, как доделаешь все исправления - выливай на фтп. Будет доступно на хосте https://new.uniqtripsoft.ru
Данные для доступа выслал в битрикс
Эндпоинты для ajax-запросов оставляй прежние - **https://uniqtrip.tmweb.ru**

**Comment by Bioss7** [comment]
Доступ получил, залил
