### ISSUE TITLE
ФУТЕР

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#15]
email меняем на info@uniqtripsoft.ru
Линки на внутренние страницы - работают
вакансии - ведет на  https://sochi.hh.ru/employer/4322397

Те страницы, которые ты не верстал - убирай из меню
Заказать звонок - модалка.

**Comment by Bioss7** [comment]
Сделал, где то мог забыть убрать ссылки, можно поправить будет на сайте, в будущем если планируется cms
