### ISSUE TITLE
ГЛАВНАЯ :: index.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#16]
- [x] Слайдер сверху. Оставить заявку - модалка
- [x] Плитка  - ссылки только на те разделы, где есть страницы. На остальных ссылка просто на #
- [x] Преимщества -  не кликабельны, добавить transition 0.3s для ховер-эффекта иконок (так приятнее)
- [x]  Успех клиентов: подробнее - ведет на /projects-visit-sochi-com.html
- [x] Успех клиентов. Не работают стрелки влево/вправо. Сделай их работающими плиз
- [x] Управление останками. Ссылки ведут на # 
- [x]  Связаться. Поменять почту на info@uniqtripsoft.ru
- [x] Найти нас на карте. Оставляем Только один офис . Пишем: Главный офис г. Сочи, Триумфальный проезд,1 , офис 2-021. С карты тоже убираем вторую метку
- [x]  Вы можете нам написать. АДЖАКС форма, должна быть рабочей

**Comment by Bioss7** [comment]
Сделал
