### ISSUE TITLE
БИТРИКС 24 :: bitrix24.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#17]
- [x] Табы - убери лишние табы (пустые).  Вообще, нужно анимацию таба сделать, ибо сейчас переключение происходит мгновенно, как-то неинтуитивно. Таб переключает только верхний блок ( с картинкой), а не всю страницу целиком
- [x] Оставить заявку - модалка (все кнопки надо сделать)
- [x] Этапы работ - некликабельны, транзишн по ховеру добавить
- [x] Успех клиентов - подробнее ведет на /projects-visit-sochi-com.html, починить стрелки
- [x] Пакеты подключения. "Подробнее" раскрывает список преимуществ
- [x] Пакеты подключения. Заказать - скролл к форме "Заказать"
- [x]  Форма заказа - проверить, чтобы работала. Пакеты внедрения - Стандартный / Расширенный / Премиум

**Comment by Bioss7** [comment]
Сделал, табы лишние убрал, сделал плавный переход для табов.
