### ISSUE TITLE
Power BI :: bi.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#18]
- [x] Табы - убрать лишниею Оставить заявку - модалка
- [x] Услуги - оставить заявку - модалка (все кнопки)
- [x] Этапы работ - не кликабельны. Ховер-эффект добавить
- [x] Успех клиентов -подробнее ведет на /projects-visit-sochi-com.html, починить стрелки
- [x] Пакеты подключения. "Подробнее" раскрывает список преимуществ
- [x] Пакеты подключения. Заказать - скролл к форме "Заказать"
- [x]  Форма заказа - проверить, чтобы работала. Пакеты внедрения - Стандартный / Расширенный / Премиум

**Comment by Bioss7** [comment]
сделал, табы тоже, но скрыл их, можно добавить в подготовленной разметке
