### ISSUE TITLE
Проекты :: projects.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#19]
- [x] Теги [Туризм], [Гостиничный бизнес], [Производство] должны филтровать плитку по тегам. Можешь на каждую плику повесить data-аттрибут с тегами. Сама плитка должна быть кликабельна.  Просто пока пусть ведет на #  
- [x] Форма заказа должна быть работающей

**Comment by Bioss7** [comment]
Добавил тег "все" чтобы была возможность показать все проекты
