### ISSUE TITLE
КОМАНДА :: our-team.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#21]
- [x] Ценности не кликабельны, ховер эффект добавить транзишн
- [x] Люди - это самый ценный актив. Стрелки починить
- [x] Стать частью команды - ведет на https://sochi.hh.ru/applicant/wantwork/payment?employerId=4322397 (в новом окне)
- [x] Форму обратной связи проверить
- [ ]

**Comment by Bioss7** [comment]
сделал
