### ISSUE TITLE
КОНТАКТЫ :: contact-us.html

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#22]
- [x]  Связаться. Поменять почту на info@uniqtripsoft.ru
- [x] Найти нас на карте. Оставляем Только один офис . Пишем: Главный офис г. Сочи, Триумфальный проезд,1 , офис 2-021. С карты тоже убираем вторую метку
- [x]  Вы можете нам написать. АДЖАКС форма, должна быть рабочей

**Comment by Bioss7** [comment]
Сделал
