### ISSUE TITLE
Вкладка ломает страницу

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#5]
https://bioss7.github.io/UniqtripSoft-pages/page2.html#
третья вкладка ломает страницу

![image](https://user-images.githubusercontent.com/10488004/177538980-03909972-e65c-4330-afc6-a4f623d78f85.png)

**Comment by Bioss7** [comment]
она не ломается, я оставил 2 таба, я думаю вы сами в разметке разместите контент
