### ISSUE TITLE
Форма обратной связи 

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#7]
https://bioss7.github.io/UniqtripSoft-pages/page1.html
https://bioss7.github.io/UniqtripSoft-pages/page5.html

Форма обратной связи  отправляет ajax запрос на **/feedback**
Форма отправляет запрос на url указанный в аттрибуте action тега form 
соответственно, в форме должно срабатывать событие submit, по которому собираем данные формы (находим внутри ноды input и textarea и собираем их имена (name) и значения
после этого отправляем это на url из action 
формат запроса POST, 
заголовок добавить **x-requested-with: xmlhttprequest** 
Формат обмена application/json
Формат тела запроса
```
{
name: string,
email: string,
message: string
}
```

Формат ответа
```
{
error: boolean,
message: text
}
```
На период отправки запроса - блокируем кнопку отправки и показываем рядом css-прелоадер, 
 типа такого  https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_loader
После получения ответа, или в случае ошибки (catch) - разблокируем кнопку, прелоадер убираем

Отобразить поле message в стандартном окне alert()

**Comment by mpouzko** [comment]
тестовый эндпоинт для отправки формы https://uniqtrip.tmweb.ru/feedback

**Comment by Bioss7** [comment]
сделал
