### ISSUE TITLE
строка поиска 

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#8]
референс https://krasnayapolyanaresort.ru/

Как это работает .
Когда в поле вводится третий символ  - блокируется ввод, показываем маленький спиннер, отправляем запрос на поиск
[GET] /search
Параметры 
```
term: string; // Строка для поиска
```

Формат ответа json
```
[
  {
    keywords: string //Это для фильтрации по результатам
    label: string; //Заголовок результата
    text: string; //Подсказка
    url: string // Ссылка для перехода
  }
]
```
Если пришел пустой масив - показать в выпадашке сообщение, что результатов нет
При вводе последующих букв - фильтруем по уже полученным результатам (Поля для поиска -keywords, label, text).

Эндпоинт для тестирования https://uniqtrip.tmweb.ru/search

**Comment by Bioss7** [comment]
сделал

**Comment by mpouzko** [comment]
Там результаты тебе отдает, смотри нетворк, можно рендерить список

**Comment by Bioss7** [comment]
Получаю результат с запроса, строкой term, в консоль выводится строка запроса в параметре
