### ISSUE TITLE
Кнопка Оставить заявку

### ISSUE THREAD

**Issue by mpouzko** [Bioss7/UniqtripSoft-pages#9]
Виджет - кнопка (их может быть неск. на странице), по нажатию на которую показыаем модальне окно с формой обратной связи
Поведение формы аналогично https://github.com/Bioss7/UniqtripSoft-pages/issues/7

**Comment by Bioss7** [comment]
https://www.figma.com/file/C2dEjKZXr7oMnpjYcstkIJ/Uniqtrip-soft?node-id=681%3A1705

**Comment by mpouzko** [comment]
Ну да, давай форму в модалке показывать, форма с молдалкой должна быть в html, просто спрятана изначально. Нажимаешь кнопку - показываем модалку

**Comment by Bioss7** [comment]
сделал модалку на странице test
